Exception:
ValueError: Intentional failure for testing.

Logging:
INFO	LoggerHook	Called 'before_node_run' with args: (Node(name=logger_hook:hello, inputs=[Literal('name')], outputs=[IO(idx=ID1)]),)
INFO	ordeq.io	Loading Literal('name')
INFO	ordeq.runner	Running node Node(name=logger_hook:hello, inputs=[Literal('name')], outputs=[IO(idx=ID1)])
INFO	LoggerHook	Called 'after_node_run' with args: (Node(name=logger_hook:hello, inputs=[Literal('name')], outputs=[IO(idx=ID1)]),)
INFO	LoggerHook	Called 'before_node_run' with args: (Node(name=logger_hook:fail),)
INFO	ordeq.runner	Running node Node(name=logger_hook:fail)
INFO	LoggerHook	Called 'on_node_call_error' with args: (Node(name=logger_hook:fail), ValueError('Intentional failure for testing.'))